baseURL = 'https://hengchaoxu.online/'
defaultContentLanguage = 'en'
locale = 'en-US'
title = 'Hengchao Harlan Xu · 许恒超'
theme = 'PaperMod'
timeZone = 'Asia/Hong_Kong'
hasCJKLanguage = true
enableRobotsTXT = true
summaryLength = 36

[pagination]
pagerSize = 10

[taxonomies]
category = 'categories'
tag = 'tags'

[outputs]
home = ['HTML', 'RSS', 'JSON']
section = ['HTML', 'RSS']
taxonomy = ['HTML', 'RSS']
term = ['HTML', 'RSS']

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
      enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
  [markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = false
  lineNos = false

[params]
description = 'Affective Computing, Spatio-Temporal Forecasting and related topics'
author = 'Hengchao Xu'
mainSections = ['posts']
defaultTheme = 'light'
disableThemeToggle = false
disableSpecial1stPost = true
math = false

ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowFullTextinRSS = true
ShowRssButtonInSectionTermList = false
ShowToc = true
TocOpen = false
hideAuthor = true
comments = true
commentsTurnstileSiteKey = ''
DateFormat = '2 January 2006'

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.35
  minMatchCharLength = 1
  ignoreLocation = true
  keys = ['title', 'permalink', 'summary', 'content']

  [params.assets]
  favicon = 'favicon.svg'
  favicon16x16 = 'favicon-16x16.png'
  favicon32x32 = 'favicon-32x32.png'
  apple_touch_icon = 'apple-touch-icon.png'
  safari_pinned_tab = 'favicon.svg'
  theme_color = '#fbfaf7'
  msapplication_TileColor = '#fbfaf7'

[[menu.main]]
name = 'Home'
url = '/'
weight = 5

[[menu.main]]
name = 'Research'
url = '/research/'
weight = 10

[[menu.main]]
name = 'Publications'
url = '/publications/'
weight = 20

[[menu.main]]
name = 'Notes'
url = '/posts/'
weight = 30

[[menu.main]]
name = 'Archives'
url = '/archives/'
weight = 40

[[menu.main]]
name = 'About'
url = '/about/'
weight = 50
